<%@ Page Title="" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="studeligibility.aspx.cs" Inherits="studeligibility" %>

<asp:Content ID="Content1" ContentPlaceHolderID="z1" Runat="Server">
 CRITERIA FOR STUDENTS ELIGIBILITY<br />
<br />
CRITERIA FOR B.COM AND BA<br />
STUDENTS MUST HAVE PASSED 12th CLASS WITH AN AGGREGATE OF 60% FROM ANY STREAM.<br /><br />
CRITERIA FOR BCA<br />
STUDENTS MUST HAVE PASSED 12th CLASS WITH AN AGGREGATE OF 65% FROM COMMERCE AND SCIENCE BACKGROUND ONLY<br /><br />
CRITERIA FOR BBM<br />
STUDENTS MUST HAVE PASSED 12TH CLASS WITH AN AGGREGATE OF 60% FROM COMMERCE BACKGROUND ONLY<br /><br />
CRITERIA FOR BSC<br />
STUDENTS MUST HAVE PASSED 12th CLASS WITH AN AGGREGATE OF 60% FROM SCIENCE BACKGROUND ONLY<br />
</asp:Content>

