using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;
using System.Data.SqlClient;
using System.Web.Security;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls.WebParts;

using System.Configuration;

public partial class teacherreg : System.Web.UI.Page
{
     SqlConnection con = new SqlConnection("Data Source=Dell\\sqlexpress;Initial Catalog=learning;Integrated Security=True;Pooling=False");
       


    string  str, tid="T180";
    SqlCommand com;
    //int count;


    protected void Page_Load(object sender, EventArgs e)
    {

        if (!IsPostBack)
        {
            autogenerated();
           
        }
    }

    void autogenerated()
    {
        //SqlConnection con = new SqlConnection(strConnString);
        String str = "select count(*) from teacherreg";
       com = new SqlCommand(str, con);
        con.Open();
        int i = Convert.ToInt16(com.ExecuteScalar());
        i++;
        runame.Text = tid+i.ToString();
        runame.Enabled = false;
        con.Close();
    }

    

    protected void rsignin_Click(object sender, EventArgs e)
    {
        //SqlConnection con = new SqlConnection("Data Source=Dell\\sqlexpress;Initial Catalog=learning;Integrated Security=True;Pooling=False");
        con.Open();

        SqlCommand cmd = new SqlCommand("Insert into teacherreg(tname,tdob,tsex,tpno,temail,taddr,tspec,tqualify,texp,tpot,tsot,thot,tat,tuname,tpw) values('" + tname.Text + "','" + tdob.Text + "','" + radiobuttonlist1.Text + "','" + tpno.Text + "','" + temail.Text + "','" + taddr.Text + "','" + tspec.Text + "','" + tqualify.Text + "','" + texp.Text + "','" + tpot.Text + "','" + tsot.Text + "','" + thot.Text + "','" + tat.Text + "','" + runame.Text + "','" + rpw.Text + "')", con);
        SqlCommand cmd1 = new SqlCommand("insert into tlogin(username,password)values('" + runame.Text + "','" + rpw.Text + "')", con);

        cmd.ExecuteNonQuery();
        cmd1.ExecuteNonQuery();
        con.Close();
        Label1.Visible = true;
    }
    protected void clear_Click(object sender, EventArgs e)
    {
        tname.Text = "";
        tdob.Text = "";
        radiobuttonlist1.Text = "";
        
        tpno.Text = "";
        temail.Text = "";
        taddr.Text = "";
        tspec.Text = "";
        tqualify.Text = "";
        texp.Text = "";
        tpot.Text = "";
        tsot.Text = "";
        thot.Text = "";
        tat.Text = "";
        runame.Text = "";
        rpw.Text = "";
        Label1.Text = "";
        autogenerated();
    }
}